DELIMITER $$
CREATE PROCEDURE AVERAGE_HOME_TEAM_SCORE_LAST_FIVE(IN TEMPORADA_ID INT, IN RODADA INT, OUT RESULT DECIMAL(5,2))
BEGIN
	SELECT SUM(PONTUACAO_GERAL_MANDANTE) / COUNT(1)
	FROM (SELECT R.PONTUACAO_GERAL_MANDANTE
					   FROM ROGERIO_REPORT_SIMPLE R 
					  WHERE R.TEMPORADA_ID = TEMPORADA_ID AND R.RODADA < RODADA
				   ORDER BY R.RODADA DESC 
					  LIMIT 5) A;
END$$
DELIMITER ;