DROP DATABASE IF EXISTS soccer_prediction;

CREATE DATABASE soccer_prediction;

USE soccer_prediction;

CREATE TABLE IF NOT EXISTS TORNEIO (
    ID INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    CONSTRAINT TRN_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TEMPORADA (
    ID INT NOT NULL,
    TORNEIO_ID INT NOT NULL,
    YEAR INT(4) NOT NULL,
    CONSTRAINT TMPRD_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CLUBE (
    ID INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    ABREVIACAO VARCHAR(3) NOT NULL,
    SLUG VARCHAR(255) NOT NULL,
    CONSTRAINT CLB_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TMP_CLUBE (
    ID INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    ABREVIACAO VARCHAR(3) NOT NULL,
    SLUG VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLUBE_TEMPORADA (
    CLUBE_ID INT NOT NULL,
    TEMPORADA_ID INT NOT NULL
);

CREATE TABLE IF NOT EXISTS POSICAO (
    ID INT NOT NULL,
    NOME VARCHAR(20) NOT NULL,
    ABREVIACAO VARCHAR(3) NOT NULL,
    CONSTRAINT PSC_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ATLETA (
    ID INT NOT NULL,
    APELIDO VARCHAR(255) NULL,
    POSICAO_ID INT NULL,
    CONSTRAINT ATLT_PK PRIMARY KEY (ID),
    CONSTRAINT ATLT_FK_01 FOREIGN KEY (POSICAO_ID) REFERENCES POSICAO(ID)
);

CREATE TABLE IF NOT EXISTS TMP_ATLETA (
    ID INT NOT NULL,
    APELIDO VARCHAR(255) NULL,
    POSICAO_ID INT NULL
);

CREATE TABLE IF NOT EXISTS ELENCO (
    ATLETA_ID INT NOT NULL,
    CLUBE_ID INT NOT NULL,
    TEMPORADA_ID INT NOT NULL,
    CONSTRAINT ELNC_PK PRIMARY KEY (ATLETA_ID, CLUBE_ID, TEMPORADA_ID),
    CONSTRAINT ELNC_FK_01 FOREIGN KEY (ATLETA_ID) REFERENCES ATLETA(ID),
    CONSTRAINT ELNC_FK_02 FOREIGN KEY (CLUBE_ID) REFERENCES CLUBE(ID),
    CONSTRAINT ELNC_FK_03 FOREIGN KEY (TEMPORADA_ID) REFERENCES TEMPORADA(ID)
);

CREATE TABLE IF NOT EXISTS TMP_ELENCO (
    ATLETA_ID INT NULL,
    CLUBE_ID INT NULL,
    TEMPORADA_ID INT NULL
);

CREATE TABLE IF NOT EXISTS PARTIDA (
    ID INT NOT NULL,
    RODADA INT NOT NULL,
    CLUBE_CASA_ID INT NOT NULL,
    CLUBE_VISITANTE_ID INT NOT NULL,
    PLACAR_OFICIAL_MANDANTE INT(2) NOT NULL,
    PLACAR_OFICIAL_VISITANTE INT(2) NOT NULL,
    TEMPORADA_ID INT NOT NULL,
    CONSTRAINT PRTD_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PONTUACAO (
    ABREVIACAO VARCHAR(2) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    PONTUACAO DECIMAL (4,2),
    CONSTRAINT PNTC_PK PRIMARY KEY (ABREVIACAO)
);

CREATE TABLE IF NOT EXISTS SCOUTS (
    ID INT NOT NULL,
    ATLETA_ID INT NOT NULL,
    RODADA INT(2) NOT NULL,
    TEMPORADA_ID INT NOT NULL,
    CLUBE_ID INT NOT NULL,
    POSICAO_ID INT NOT NULL,
    PARTICIPOU INT NOT NULL,
    PONTOS_NUM DECIMAL(4,2) NULL,
    PARTIDA_ID INT NOT NULL,
    TITULAR INT NOT NULL,
    SUBSTITUIDO INT NULL,
    TEMPO_JOGADO DECIMAL(3,2) NULL,
    NOTA DECIMAL(4,2) NULL,
    FS INT NULL,
    PE INT NULL,
    A INT NULL,
    FT INT NULL,
    FD INT NULL,
    FF INT NULL,
    G INT NULL,
    I INT NULL,
    PP INT NULL,
    RB INT NULL,
    FC INT NULL,
    GC INT NULL,
    CA INT NULL,
    CV INT NULL,
    SG INT NULL,
    DD INT NULL,
    DP INT NULL,
    GS INT NULL,
    CONSTRAINT SCTS_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TMP_TEAM_POWER_SIMPLE (
	PARTIDA_ID INT NOT NULL,
    PONTUACAO_GERAL_MANDANTE DECIMAL(5,2) NOT NULL,
    PONTUACAO_GERAL_VISITANTE DECIMAL(5,2) NOT NULL,
    CONSTRAINT TMP_TM_PWR_SMPL_PK PRIMARY KEY (PARTIDA_ID),
    CONSTRAINT TMP_TM_PWR_SMPL_FK_01 FOREIGN KEY (PARTIDA_ID) REFERENCES PARTIDA(ID)
);

CREATE TABLE IF NOT EXISTS TMP_TEAM_POWER_HISTORICAL (
	PARTIDA_ID INT NOT NULL,
    PONTUACAO_GERAL_MANDANTE DECIMAL(5,2) NOT NULL,
    PONTUACAO_GERAL_VISITANTE DECIMAL(5,2) NOT NULL,
    CONSTRAINT TMP_TM_PWR_HSTRCL_PK PRIMARY KEY (PARTIDA_ID),
    CONSTRAINT TMP_TM_PWR_HSTRCL_FK_01 FOREIGN KEY (PARTIDA_ID) REFERENCES PARTIDA(ID)
);

CREATE TABLE IF NOT EXISTS TMP_INPUT_REDE_NEURAL(
	MEDIA_GOLS_REALIZADOS_MANDANTE DECIMAL(3,2) NOT NULL,
    MEDIA_GOLS_SOFRIDOS_MANDANTE DECIMAL(3,2) NOT NULL,
    MEDIA_GOLS_REALIZADOS_VISITANTE DECIMAL(3,2) NOT NULL,
    MEDIA_GOLS_SOFRIDOS_VISITANTE DECIMAL(3,2) NOT NULL,
    NUM_VITORIAS_ULTIMOS_5_JOGOS_MANDANTE INT NOT NULL,
    NUM_EMPATES_ULTIMOS_5_JOGOS_MANDANTE INT NOT NULL,
    NUM_DERROTAS_ULTIMOS_5_JOGOS_MANDANTE INT NOT NULL,
    NUM_VITORIAS_ULTIMOS_5_JOGOS_VISITANTE INT NOT NULL,
    NUM_EMPATES_ULTIMOS_5_JOGOS_VISITANTE INT NOT NULL,
    NUM_DERROTAS_ULTIMOS_5_JOGOS_VISITANTE INT NOT NULL,
    FORCA_MANDANTE DECIMAL(5,2) NOT NULL,
    FORCA_VISITANTE DECIMAL(5,2) NOT NULL,
    RESULTADO INT NOT NULL
);