# CLUBE
INSERT INTO CLUBE (ID, NOME, ABREVIACAO, SLUG)
	SELECT C.ID, C.NOME, C.ABREVIACAO, C.SLUG
	FROM TMP_CLUBE C
	WHERE 1 = 1
	GROUP BY C.ID, C.NOME, C.ABREVIACAO, C.SLUG
	ORDER BY C.ID;
    
DROP TABLE TMP_CLUBE;

# ATLETA
INSERT INTO ATLETA (ID, APELIDO, POSICAO_ID)
	SELECT A.ID AS ID, MIN(A.APELIDO) AS APELIDO, MAX(A.POSICAO_ID) AS POSICAO_ID
	FROM TMP_ATLETA A
	WHERE 1 = 1
    AND A.POSICAO_ID != 0
	GROUP BY A.ID
	ORDER BY A.ID;

DROP TABLE TMP_ATLETA;

# ELENCO
INSERT INTO ELENCO (ATLETA_ID, CLUBE_ID, TEMPORADA_ID)
	SELECT E.ATLETA_ID, E.CLUBE_ID, E.TEMPORADA_ID
	FROM TMP_ELENCO E
	WHERE 1 = 1
	AND E.CLUBE_ID IS NOT NULL 
	AND E.CLUBE_ID != 0;

DROP TABLE TMP_ELENCO;

# SCOUTS
## POSICAO
CREATE TABLE TMP_FIX (SCOUTS_ID INT, POSICAO_ID INT);

INSERT INTO TMP_FIX (SCOUTS_ID, POSICAO_ID)
	SELECT S.ID, A.POSICAO_ID
	FROM SCOUTS S
	JOIN ATLETA A ON S.ATLETA_ID = A.ID
	JOIN POSICAO P ON A.POSICAO_ID = P.ID
	WHERE S.POSICAO_ID = 0;

UPDATE SCOUTS S 
	JOIN TMP_FIX T ON S.ID = T.SCOUTS_ID
SET S.POSICAO_ID = T.POSICAO_ID;

DROP TABLE TMP_FIX;

## PARTIDA
CREATE TABLE TMP_FIX (SCOUTS_ID INT, PARTIDA_ID INT);

INSERT INTO TMP_FIX (SCOUTS_ID, PARTIDA_ID)
	SELECT S.ID, P.ID
	FROM SCOUTS S
	JOIN ELENCO E ON E.ATLETA_ID = S.ATLETA_ID AND E.TEMPORADA_ID = S.TEMPORADA_ID
	JOIN PARTIDA P ON P.RODADA = S.RODADA AND P.TEMPORADA_ID = S.TEMPORADA_ID AND (P.CLUBE_CASA_ID = E.CLUBE_ID OR P.CLUBE_VISITANTE_ID = E.CLUBE_ID)
	WHERE S.PARTIDA_ID = 0;

UPDATE SCOUTS S 
	JOIN TMP_FIX T ON S.ID = T.SCOUTS_ID
SET S.PARTIDA_ID = T.PARTIDA_ID;

DROP TABLE TMP_FIX;

DELETE FROM SCOUTS WHERE PARTIDA_ID = 0;

## CLUBE
CREATE TABLE TMP_FIX (SCOUTS_ID INT, CLUBE_ID INT);

INSERT INTO TMP_FIX (SCOUTS_ID, CLUBE_ID)
	SELECT S.ID, E.CLUBE_ID
	FROM SCOUTS S
	JOIN ELENCO E ON S.ATLETA_ID = E.ATLETA_ID AND S.TEMPORADA_ID = E.TEMPORADA_ID
	WHERE S.CLUBE_ID = 0;
    
UPDATE SCOUTS S 
	JOIN TMP_FIX T ON S.ID = T.SCOUTS_ID
SET S.CLUBE_ID = T.CLUBE_ID;

DROP TABLE TMP_FIX;

## MAIS SOBRE PARTIDA
CREATE TABLE TMP_FIX (SCOUTS_ID INT, PARTIDA_ID INT);

INSERT INTO TMP_FIX (SCOUTS_ID, PARTIDA_ID)
	SELECT S.ID, P.ID
	FROM SCOUTS S
	JOIN PARTIDA P ON P.RODADA = S.RODADA AND P.TEMPORADA_ID = S.TEMPORADA_ID AND (P.CLUBE_CASA_ID = S.CLUBE_ID OR P.CLUBE_VISITANTE_ID = S.CLUBE_ID)
	WHERE 1 = 1
	AND S.PARTIDA_ID NOT IN (SELECT P.ID FROM PARTIDA P);
    
UPDATE SCOUTS S 
	JOIN TMP_FIX T ON S.ID = T.SCOUTS_ID
SET S.PARTIDA_ID = T.PARTIDA_ID;

DROP TABLE TMP_FIX;

# Fixes
UPDATE SCOUTS S
SET S.PARTICIPOU = 1
WHERE S.PONTOS_NUM != 0;

UPDATE SCOUTS S
SET S.PARTICIPOU = 1
WHERE S.TITULAR = 1;

INSERT INTO TMP_TEAM_POWER_SIMPLE (PARTIDA_ID, PONTUACAO_GERAL_MANDANTE, PONTUACAO_GERAL_VISITANTE)
	SELECT R.ID, R.PONTUACAO_GERAL_MANDANTE, R.PONTUACAO_GERAL_VISITANTE
	FROM ROGERIO_REPORT_SIMPLE R
    WHERE R.TEMPORADA_ID = 1;

INSERT INTO TMP_TEAM_POWER_HISTORICAL (PARTIDA_ID, PONTUACAO_GERAL_MANDANTE, PONTUACAO_GERAL_VISITANTE)
	SELECT R.ID, R.PONTUACAO_GERAL_MANDANTE, R.PONTUACAO_GERAL_VISITANTE
	FROM ROGERIO_REPORT_HISTORICAL R
    WHERE R.TEMPORADA_ID = 1 AND R.RODADA > 1;


########################

INSERT INTO TMP_INPUT_REDE_NEURAL(
	MEDIA_GOLS_REALIZADOS_MANDANTE,
    MEDIA_GOLS_SOFRIDOS_MANDANTE,
    MEDIA_GOLS_REALIZADOS_VISITANTE,
    MEDIA_GOLS_SOFRIDOS_VISITANTE,
    NUM_VITORIAS_ULTIMOS_5_JOGOS_MANDANTE,
    NUM_EMPATES_ULTIMOS_5_JOGOS_MANDANTE,
    NUM_DERROTAS_ULTIMOS_5_JOGOS_MANDANTE,
    NUM_VITORIAS_ULTIMOS_5_JOGOS_VISITANTE,
    NUM_EMPATES_ULTIMOS_5_JOGOS_VISITANTE,
    NUM_DERROTAS_ULTIMOS_5_JOGOS_VISITANTE,
    FORCA_MANDANTE,
    FORCA_VISITANTE,
    RESULTADO
)
	SELECT 
		(
			SELECT SUM(CASE WHEN P.CLUBE_CASA_ID = P1.CLUBE_CASA_ID THEN P1.PLACAR_OFICIAL_MANDANTE ELSE P1.PLACAR_OFICIAL_VISITANTE END) / COUNT(1)
			FROM PARTIDA P1
			WHERE 1 = 1
			AND P1.RODADA < P.RODADA
			AND (P.CLUBE_CASA_ID = P1.CLUBE_CASA_ID OR P.CLUBE_CASA_ID = P1.CLUBE_VISITANTE_ID)
			AND P.TEMPORADA_ID = P1.TEMPORADA_ID
		) AS MEDIA_GOLS_REALIZADOS_MANDANTE,
		(
			SELECT SUM(CASE WHEN P.CLUBE_CASA_ID = P1.CLUBE_CASA_ID THEN P1.PLACAR_OFICIAL_VISITANTE ELSE P1.PLACAR_OFICIAL_MANDANTE END) / COUNT(1)
			FROM PARTIDA P1
			WHERE 1 = 1
			AND P1.RODADA < P.RODADA
			AND (P.CLUBE_CASA_ID = P1.CLUBE_CASA_ID OR P.CLUBE_CASA_ID = P1.CLUBE_VISITANTE_ID)
			AND P.TEMPORADA_ID = P1.TEMPORADA_ID
		) AS MEDIA_GOLS_SOFRIDOS_MANDANTE,
		(
			SELECT SUM(CASE WHEN P.CLUBE_VISITANTE_ID = P1.CLUBE_CASA_ID THEN P1.PLACAR_OFICIAL_MANDANTE ELSE P1.PLACAR_OFICIAL_VISITANTE END) / COUNT(1)
			FROM PARTIDA P1
			WHERE 1 = 1
			AND P1.RODADA < P.RODADA
			AND (P.CLUBE_VISITANTE_ID = P1.CLUBE_CASA_ID OR P.CLUBE_VISITANTE_ID = P1.CLUBE_VISITANTE_ID)
			AND P.TEMPORADA_ID = P1.TEMPORADA_ID
		) AS MEDIA_GOLS_REALIZADOS_VISITANTE,
		(
			SELECT SUM(CASE WHEN P.CLUBE_VISITANTE_ID = P1.CLUBE_CASA_ID THEN P1.PLACAR_OFICIAL_VISITANTE ELSE P1.PLACAR_OFICIAL_MANDANTE END) / COUNT(1)
			FROM PARTIDA P1
			WHERE 1 = 1
			AND P1.RODADA < P.RODADA
			AND (P.CLUBE_VISITANTE_ID = P1.CLUBE_CASA_ID OR P.CLUBE_VISITANTE_ID = P1.CLUBE_VISITANTE_ID)
			AND P.TEMPORADA_ID = P1.TEMPORADA_ID
		) AS MEDIA_GOLS_SOFRIDOS_VISITANTE,
		(
			SELECT SUM(
					CASE WHEN P.CLUBE_CASA_ID = P1.CLUBE_CASA_ID THEN 
						CASE WHEN P1.PLACAR_OFICIAL_MANDANTE > P1.PLACAR_OFICIAL_VISITANTE THEN
							1
						ELSE
							0
						END
					ELSE 
						CASE WHEN P1.PLACAR_OFICIAL_MANDANTE < P1.PLACAR_OFICIAL_VISITANTE THEN
							1
						ELSE
							0
						END
					END)
			FROM PARTIDA P1
			WHERE 1 = 1
			AND P1.RODADA BETWEEN P.RODADA - 5 AND P.RODADA - 1
			AND (P.CLUBE_CASA_ID = P1.CLUBE_CASA_ID OR P.CLUBE_CASA_ID = P1.CLUBE_VISITANTE_ID)
			AND P.TEMPORADA_ID = P1.TEMPORADA_ID
		) AS NUM_VITORIAS_ULTIMOS_5_JOGOS_MANDANTE,
		(
			SELECT SUM(
						CASE WHEN P1.PLACAR_OFICIAL_MANDANTE = P1.PLACAR_OFICIAL_VISITANTE THEN
							1
						ELSE
							0
						END)
			FROM PARTIDA P1
			WHERE 1 = 1
			AND P1.RODADA BETWEEN P.RODADA - 5 AND P.RODADA - 1
			AND (P.CLUBE_CASA_ID = P1.CLUBE_CASA_ID OR P.CLUBE_CASA_ID = P1.CLUBE_VISITANTE_ID)
			AND P.TEMPORADA_ID = P1.TEMPORADA_ID
		) AS NUM_EMPATES_ULTIMOS_5_JOGOS_MANDANTE,
		(
			SELECT SUM(
					CASE WHEN P.CLUBE_CASA_ID = P1.CLUBE_CASA_ID THEN 
						CASE WHEN P1.PLACAR_OFICIAL_MANDANTE < P1.PLACAR_OFICIAL_VISITANTE THEN
							1
						ELSE
							0
						END
					ELSE 
						CASE WHEN P1.PLACAR_OFICIAL_MANDANTE > P1.PLACAR_OFICIAL_VISITANTE THEN
							1
						ELSE
							0
						END
					END)
			FROM PARTIDA P1
			WHERE 1 = 1
			AND P1.RODADA BETWEEN P.RODADA - 5 AND P.RODADA - 1
			AND (P.CLUBE_CASA_ID = P1.CLUBE_CASA_ID OR P.CLUBE_CASA_ID = P1.CLUBE_VISITANTE_ID)
			AND P.TEMPORADA_ID = P1.TEMPORADA_ID
		) AS NUM_DERROTAS_ULTIMOS_5_JOGOS_MANDANTE,
		(
			SELECT SUM(
					CASE WHEN P.CLUBE_VISITANTE_ID = P1.CLUBE_CASA_ID THEN 
						CASE WHEN P1.PLACAR_OFICIAL_MANDANTE > P1.PLACAR_OFICIAL_VISITANTE THEN
							1
						ELSE
							0
						END
					ELSE 
						CASE WHEN P1.PLACAR_OFICIAL_MANDANTE < P1.PLACAR_OFICIAL_VISITANTE THEN
							1
						ELSE
							0
						END
					END)
			FROM PARTIDA P1
			WHERE 1 = 1
			AND P1.RODADA BETWEEN P.RODADA - 5 AND P.RODADA - 1
			AND (P.CLUBE_VISITANTE_ID = P1.CLUBE_CASA_ID OR P.CLUBE_VISITANTE_ID = P1.CLUBE_VISITANTE_ID)
			AND P.TEMPORADA_ID = P1.TEMPORADA_ID
		) AS NUM_VITORIAS_ULTIMOS_5_JOGOS_VISITANTE,
		(
			SELECT SUM(
						CASE WHEN P1.PLACAR_OFICIAL_MANDANTE = P1.PLACAR_OFICIAL_VISITANTE THEN
							1
						ELSE
							0
						END)
			FROM PARTIDA P1
			WHERE 1 = 1
			AND P1.RODADA BETWEEN P.RODADA - 5 AND P.RODADA - 1
			AND (P.CLUBE_VISITANTE_ID = P1.CLUBE_CASA_ID OR P.CLUBE_VISITANTE_ID = P1.CLUBE_VISITANTE_ID)
			AND P.TEMPORADA_ID = P1.TEMPORADA_ID
		) AS NUM_EMPATES_ULTIMOS_5_JOGOS_VISITANTE,
		(
			SELECT SUM(
					CASE WHEN P.CLUBE_VISITANTE_ID = P1.CLUBE_CASA_ID THEN 
						CASE WHEN P1.PLACAR_OFICIAL_MANDANTE < P1.PLACAR_OFICIAL_VISITANTE THEN
							1
						ELSE
							0
						END
					ELSE 
						CASE WHEN P1.PLACAR_OFICIAL_MANDANTE > P1.PLACAR_OFICIAL_VISITANTE THEN
							1
						ELSE
							0
						END
					END)
			FROM PARTIDA P1
			WHERE 1 = 1
			AND P1.RODADA BETWEEN P.RODADA - 5 AND P.RODADA - 1
			AND (P.CLUBE_VISITANTE_ID = P1.CLUBE_CASA_ID OR P.CLUBE_VISITANTE_ID = P1.CLUBE_VISITANTE_ID)
			AND P.TEMPORADA_ID = P1.TEMPORADA_ID
		) AS NUM_DERROTAS_ULTIMOS_5_JOGOS_VISITANTE,
		TH.PONTUACAO_GERAL_MANDANTE AS FORCA_MANDANTE,
		TH.PONTUACAO_GERAL_VISITANTE AS FORCA_VISITANTE,
		(CASE 
			WHEN P.PLACAR_OFICIAL_MANDANTE > P.PLACAR_OFICIAL_VISITANTE THEN 1
			WHEN P.PLACAR_OFICIAL_MANDANTE = P.PLACAR_OFICIAL_VISITANTE THEN 2
			WHEN P.PLACAR_OFICIAL_MANDANTE < P.PLACAR_OFICIAL_VISITANTE THEN 3
		 END) AS RESULTADO
	FROM PARTIDA P
	JOIN TMP_TEAM_POWER_HISTORICAL TH ON P.ID = TH.PARTIDA_ID
	WHERE 1 = 1
	AND P.RODADA > 5
	AND P.TEMPORADA_ID = 1;

