# CLUBE_TEMPORADA
ALTER TABLE CLUBE_TEMPORADA ADD CONSTRAINT CLB_TMPRD_PK PRIMARY KEY (CLUBE_ID,TEMPORADA_ID);
ALTER TABLE CLUBE_TEMPORADA ADD CONSTRAINT CLB_TMPRD_PK_01 FOREIGN KEY (CLUBE_ID) REFERENCES CLUBE(ID) ON DELETE CASCADE;
ALTER TABLE CLUBE_TEMPORADA ADD CONSTRAINT CLB_TMPRD_PK_02 FOREIGN KEY (TEMPORADA_ID) REFERENCES TEMPORADA(ID) ON DELETE CASCADE;

# PARTIDA
ALTER TABLE PARTIDA ADD CONSTRAINT PRTD_FK_01 FOREIGN KEY (CLUBE_CASA_ID) REFERENCES CLUBE(ID) ON DELETE CASCADE;
ALTER TABLE PARTIDA ADD CONSTRAINT PRTD_FK_02 FOREIGN KEY (CLUBE_VISITANTE_ID) REFERENCES CLUBE(ID) ON DELETE CASCADE;
ALTER TABLE PARTIDA ADD CONSTRAINT PRTD_FK_03 FOREIGN KEY (TEMPORADA_ID) REFERENCES TEMPORADA(ID) ON DELETE CASCADE;

# SCOUTS
ALTER TABLE SCOUTS ADD CONSTRAINT SCTS_FK_01 FOREIGN KEY (ATLETA_ID) REFERENCES ATLETA(ID) ON DELETE CASCADE;
ALTER TABLE SCOUTS ADD CONSTRAINT SCTS_FK_02 FOREIGN KEY (CLUBE_ID) REFERENCES CLUBE(ID) ON DELETE CASCADE;
ALTER TABLE SCOUTS ADD CONSTRAINT SCTS_FK_03 FOREIGN KEY (TEMPORADA_ID) REFERENCES TEMPORADA(ID) ON DELETE CASCADE;
ALTER TABLE SCOUTS ADD CONSTRAINT SCTS_FK_04 FOREIGN KEY (PARTIDA_ID) REFERENCES PARTIDA(ID) ON DELETE CASCADE;

# TEMPORADA
ALTER TABLE TEMPORADA ADD CONSTRAINT TMPRD_FK_01 FOREIGN KEY (TORNEIO_ID) REFERENCES TORNEIO(ID) ON DELETE CASCADE;