SELECT P.TEMPORADA_ID, COUNT(1) FROM PARTIDA P GROUP BY P.TEMPORADA_ID; # Quantidade de partidas por temporada
SELECT COUNT(1) FROM CLUBE_TEMPORADA CT GROUP BY CT.TEMPORADA_ID; # Quantidade de times por temporada

SELECT P.ID, P.RODADA FROM PARTIDA P WHERE P.TEMPORADA_ID = 2 AND P.ID NOT IN (SELECT S.PARTIDA_ID FROM SCOUTS S); # Faltando scouts das rodadas 26 e 38 de 2015!

# Scouts de partidas por temporada
SELECT A.TEMPORADA_ID, COUNT(1)
FROM (
SELECT S.TEMPORADA_ID AS TEMPORADA_ID, COUNT(1)
FROM SCOUTS S
GROUP BY S.TEMPORADA_ID, S.PARTIDA_ID
) A
GROUP BY A.TEMPORADA_ID;

# Somente scouts da temporada 2014 marcaram o jogador como titular!
SELECT S.TEMPORADA_ID, S.PARTIDA_ID, S.CLUBE_ID
FROM SCOUTS S
WHERE 1 = 1
AND S.TEMPORADA_ID = 1
GROUP BY S.TEMPORADA_ID, S.PARTIDA_ID, S.CLUBE_ID
HAVING SUM(TITULAR) = 12;

# Temporada 2015 não marcou muitos scouts como Participou
SELECT S.TEMPORADA_ID, S.PARTIDA_ID, S.CLUBE_ID
FROM SCOUTS S
WHERE 1 = 1
AND S.TEMPORADA_ID = 2
GROUP BY S.TEMPORADA_ID, S.PARTIDA_ID, S.CLUBE_ID
HAVING SUM(S.PARTICIPOU) >= 12;

# Temporada 2015 aparentemente não registrou todos os scouts corretamente
SELECT S.TEMPORADA_ID, S.PARTIDA_ID, S.CLUBE_ID
FROM SCOUTS S
WHERE 1 = 1
AND S.TEMPORADA_ID = 3
GROUP BY S.TEMPORADA_ID, S.PARTIDA_ID, S.CLUBE_ID
HAVING SUM(CASE WHEN S.PONTOS_NUM != 0 THEN 1 ELSE 0 END) >= 12;



######################


# Análise Pontuação geral vs Resultado
SELECT COUNT(1)
FROM ROGERIO_REPORT_SIMPLE R 
WHERE 1 = 1
AND R.TEMPORADA_ID = 1
AND ((R.PONTUACAO_GERAL_MANDANTE > PONTUACAO_GERAL_VISITANTE AND R.PLACAR_OFICIAL_MANDANTE < R.PLACAR_OFICIAL_VISITANTE) OR
	 (R.PONTUACAO_GERAL_MANDANTE < PONTUACAO_GERAL_VISITANTE AND R.PLACAR_OFICIAL_MANDANTE > R.PLACAR_OFICIAL_VISITANTE));