CREATE VIEW ROGERIO_REPORT_SIMPLE AS

SELECT P.ID, 
	   P.CLUBE_CASA_ID,
       P.CLUBE_VISITANTE_ID,
       (
			SELECT SUM(S.PONTOS_NUM) FROM SCOUTS S WHERE S.PARTIDA_ID = P.ID AND S.CLUBE_ID = P.CLUBE_CASA_ID AND S.TITULAR
       ) AS PONTUACAO_GERAL_MANDANTE,
       (
			SELECT SUM(S.PONTOS_NUM) FROM SCOUTS S WHERE S.PARTIDA_ID = P.ID AND S.CLUBE_ID = P.CLUBE_VISITANTE_ID AND S.TITULAR
       ) AS PONTUACAO_GERAL_VISITANTE,
       P.PLACAR_OFICIAL_MANDANTE,
       P.PLACAR_OFICIAL_VISITANTE,
       P.RODADA,
       P.TEMPORADA_ID
FROM PARTIDA P
WHERE 1 = 1;